---
title: "Module 6"
subtitle: "Concept of tidy data, vectors and pivoting"
editor: source
params:
    module: 6
execute: 
  echo: false
  warning: false
---

## {{< fa bullseye >}} Learning Objectives

```{r}

lobj1 <- readr::read_csv(here::here("data/tbl-02-learning-objectives.csv")) |> 
  dplyr::filter(module == params$module) |>
  dplyr::pull(learning_objectives)

```

1. `r lobj1[1]`
2. `r lobj1[2]`
3. `r lobj1[3]`

## {{< fa display >}} Slides

[View slides in full screen](../slides/lec-04-tidy-data.html) | [Download slides as PDF]({{< var course.github-org >}}/website/raw/main/slides/lec-04-tidy-data.pdf)

```{=html}
<iframe class="slide-deck" src="../slides/lec-04-tidy-data.html" height="420" width="747" style="border: 1px solid #123233;"></iframe>
```

## {{< fa book >}} Readings

1. Read [R for Data Science - Section 12 - Tidy data](https://r4ds.had.co.nz/tidy-data.html)  
2. Read [R for Data Science - Section 15 - Factors](https://r4ds.had.co.nz/factors.html#factors)  

## {{< fa code >}} Homework assignment 

Homework assignment & learning reflection due: [**{{< var md-06.homework-due >}}**]{.highlight-yellow}

Complete the homework programming assignments that are in your project folder for Module 6 on [Posit Cloud]({{< var platforms.posit-cloud >}}content/all):

- hw-tidyr.qmd

Complete the following assignment, which is not documented in your Module 6 project folder:

- [HW: Capstone Project Data Exploration](../assignments/hw-05-project-data-exploration.qmd) 

## {{< fa pen-clip >}} Learning reflection

Complete the learning reflection that is in your project folder for Module 6 by [**{{< var md-06.homework-due >}}**]{.highlight-yellow} on [Posit Cloud]({{< var platforms.posit-cloud >}}content/all) 

- learning-06.qmd
