project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "CVEN 5999 - Summer 2026"
  description: "Homepage for Special Topics - Data Analytics for Development"
  site-url: "https://cven5999-ss26.github.io/website/"
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2026, Lars Schöbitz"
    background: "#D9E3E4"
  
  sidebar:
    background: "#D9E3E4"
    logo: "img/logo.png"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1
    tools:
      - icon: github
        href: https://github.com/cven5999-ss26
        text: "GitHub organization"
    contents:
      - href: index.qmd
        text: Course Overview
      - text: "---"
      - section: "Module 1"
        href: modules/md-01.qmd
        contents:
          - href: assignments/md-01/am-01-1-github-account.qmd
            text: "am-01-1: GitHub account"
          - href: assignments/md-01/am-01-2-orcid.qmd
            text: "am-01-2: ORCID iD"
          - href: assignments/md-01/am-01-3-posit-cloud.qmd
            text: "am-01-3: Posit Cloud"
          - href: assignments/md-01/am-01-4-github-pat.qmd
            text: "am-01-4: GitHub PAT"
          - href: assignments/md-01/am-01-5-github-clone.qmd
            text: "am-01-5: GitHub clone"
          - href: assignments/md-01/am-01-6-github-workflow.qmd
            text: "am-01-6: GitHub workflow"
          - href: assignments/md-01/am-01-7-pre-course-survey.qmd
            text: "am-01-7: Pre-course survey"
          - href: assignments/md-01/am-01-8-github-issue.qmd
            text: "am-01-8: GitHub issue"
      - href: modules/md-02.qmd
        text: "Module 2"
      - section: "Module 3"
        href: modules/md-03.qmd
        contents:
          - href: assignments/md-03/am-03-1-bookmarks.qmd
            text: "am-03-1: Bookmarks"
      - href: modules/md-04.qmd
        text: "Module 4"
      - href: modules/md-05.qmd
        text: "Module 5"
      - href: modules/md-06.qmd
        text: "Module 6"
      - href: modules/md-07.qmd
        text: "Module 7"
      - text: "---"
      - href: "project/index.qmd"
        text: "Capstone Project"
        

format:
  html:
    theme:
      light: [litera, theme.scss]
    code-copy: true
    code-overflow: wrap
    link-external-icon: true
    link-external-newwindow: true
    toc: true
    mainfont: "Atkinson Hyperlegible"
    include-in-header:
        - text: |
            <script defer data-domain="cven5999-ss26.github.io/website/" src="https://plausible.io/js/script.js"></script>

freeze: auto
editor: source