---
title: "Week 4"
subtitle: "Data transformation with dplyr"
editor: source
params:
    week: 4
execute: 
  echo: false
  warning: false
---


## {{< fa bullseye >}} Learning Objectives

```{r}
#| echo: false

lobj1 <- readr::read_csv(here::here("data/tbl-02-learning-objectives.csv")) |> 
  dplyr::filter(week == params$week) |>
  dplyr::pull(learning_objectives)

```

1. `r lobj1[1]`

## {{< fa display >}} Slides

[View slides in full screen](../slides/lec-03-transformation.html) | [Download slides as PDF]({{< var course.github-org >}}/website/raw/main/slides/lec-03-transformation.pdf)

```{=html}
<iframe class="slide-deck" src="../slides/lec-03-transformation.html" height="420" width="747" style="border: 1px solid #123233;"></iframe>
```

## {{< fa book >}} Readings

1. Read [R for Data Science - Section 5 - Data transformation](https://r4ds.had.co.nz/transform.html)  
2. Read [Excuse Me, Do You Have a Moment to Talk About Version Control?](https://www.tandfonline.com/doi/full/10.1080/00031305.2017.1399928)

## {{< fa code >}} Homework assignment 

Homework assignment & learning reflection due: [**{{< var md-04.homework-due >}}**]{.highlight-yellow}

Complete the homework programming assignments that are in your project folder for week 4 on [Posit Cloud]({{< var platforms.posit-cloud >}}content/all)

- hw-data-transformation.qmd

Complete the following assignment, which is not documented in your week 4 project folder:

- [HW: Capstone Project Setup](../assignments/hw-04b-capstone-project-setup.qmd): Set up your capstone project repository

## {{< fa pen-clip >}} Learning reflection

Complete the learning reflection that is in your project folder for week 4 by [**{{< var md-04.homework-due >}}**]{.highlight-yellow} on [Posit Cloud]({{< var platforms.posit-cloud >}}content/all)

- learning-04.qmd
